# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32d88892228d68891cf0033689b0313296cee11834c7195be9cf38feedcd79b4eeac47908077fd8a9db37a6332fba1dd25cedbd37bfb10c89c35609268835082

test:
  secret_key_base: 4d5119658cc441d8e791c0cf6d7c294c105d1e7ceda5c0df47c9b2d587e47266fe0aa3a7d553ef4e5cb434cb4b0f99af775490be0557cf3f1ecd239c69617443

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
